### ISSUE TITLE
URLs not converting to embedded content

### ISSUE THREAD

**Issue by learningtechnologyservices** [frederic-nevers/moodle-filter_multiembed#1]
Hi Frederic, the sample test URLs are not converting to embedded content for me in edited page views, so I'm not able to see the content as expected. I've followed the readme instructions about enabling the filter and the convert URLs one, as you can see from my page settings screenshot.
I did testing with one URL, multiple URLs and also with a <a> tag, as your code seems dependent on that, which might not be how a teacher might expect to use this.
![multiembed_page_oneurl1](https://cloud.githubusercontent.com/assets/4713457/20282544/0ee03136-aaad-11e6-90ec-6c92df4d9a7c.png)

![multiembed_page_oneurl_filtersettings1](https://cloud.githubusercontent.com/assets/4713457/20282550/14d379f4-aaad-11e6-9f1d-ac550fb1e5cd.png)

**Comment by frederic-nevers** [comment]
Hi Karen, 

Thank you very much for reviewing the plugin, your comments are much appreciated. Regarding the issue you describe, I am unable to reproduce the behaviour you mention. 

I suspect it is something to do with 'Allow EMBED and OBJECT tags' and 'Allow frame embedding' not being set to ‘yes’ on your setup. I have changed the usage instructions to reflect this. Could you please let me know if that solves your issue? 

Thanks, 
Fred

**Comment by learningtechnologyservices** [comment]
Hi Fred, good point on needing to enable the "Allow EMBED and OBJECT tags" setting and thanks for adding it to the documentation! 

However, I'm not sure how the "Allow frame embedding" setting contributes, it's not encouraged for security reasons and even with it enabled and with a purge of all caches, the URL for TED still isn't working while I'm able to get a Youtube embedded URL to display correctly in the same location so the code to rewrite the content doesn't appear to be taking effect.

![multiembed_coursepage](https://cloud.githubusercontent.com/assets/4713457/20328701/2584f6bc-ab8c-11e6-82e4-8b193e9bf683.png)

**Comment by frederic-nevers** [comment]
Hi Karen, 

Thank you for your prompt reply. I have been able to reproduce the issue you are referring to on a vanilla 3.0 site. I have found where the problem lies.
The 'Convert URLs into links and images' filter needs to be applied to all formats (Site administration ▶︎ Plugins ▶︎ Filters ▶︎ Convert URLs into links and images). By default, only the 'Moodle auto-format' is filtered, when HTML (and other methods) should also be filtered for the 'Multi-embed' filter to work as expected. 

You are correct in that the 'Allow frame embedding' does not necessarily need to be enabled for this to work. 

I have updated the plugin documentation, and will update the Readme file some time later today. I am sorry you have had to perform troubleshooting, and I thank you for being very thorough - the documentation is now better because of it. 

Cheers, 
Fred

<img width="866" alt="screen shot 2016-11-16 at 10 39 03 am" src="https://cloud.githubusercontent.com/assets/1598047/20332730/f112bbaa-abe8-11e6-9e1b-8501e026e1a4.png">
